### ISSUE TITLE
Question about Face Verification

### ISSUE THREAD

**Issue by ahkarami** [JudasDie/deeplearning.ai#3]
Dear @JudasDie,
Thank you for your fantastic repository. I have a question about your **Face Verification** system (week4, Section 3.1). Your designed face verification system requires a predefined _threshold_ (_e.g._, 0.7). Choosing an appropriate _threshold_ value would be an annoying issue. In order to design a _face verification_ system which doesn't require threshold, and clearly defines the same/different faces status of two input face images, I think it is better to design a new system such as below (_i.e.,_ In fact, I want to design a _Siamese Face Verification_ system which produces the confidence score of two input faces, which belong to the same face or different one):
1- By using the _FaceNet_ pre-trained weights one can extract the 128-dimensional embedding of two input faces. 
2- Compute the L2 distance (or maybe L1 distance) of these two embeddings.  
3- Pass the above-mentioned 128 vector to a Fully connected layer (128->2) followed by a Sigmoid (In order to get the confidence score of each class (_i.e.,_ Same Face class or Different Face class)).
and we just need to train the last mentioned Fully Connected layer. 
I want to ask you that does this mentioned solution correct? What's your opinion?
I would really appropriate if you can help me.

**Comment by JudasDie** [comment]
Thank you for your trust first. And I think there is an issue about your way, which step2 and step3 are in a conflict. If you have computed L2 distance, why use fc layer again? You can just compare distances. If you really want to use fc layer to compare similarity between 128-dimensional embeddings, just pass these features to fc layer, no need to computer L2. And, sigmoid fc layer with 2 outputs is not a good way, since the train examples will push the output to approximate 0.501 and 0.499 for right and wrong output. For example, if the label is 1, two outputs will be approximate 0.501 for 1 and approximate 0.499 for 0.  That happens since your network wanna get a lower error for your cost function. So if you want to get a confidence for 2-class mission, just use one output rather than two (the closer to 1, more confidence for positive label). 
That's my opion.

**Comment by JudasDie** [comment]
Reply @ahkarami 
Thank you for your trust first. And I think there is an issue about your way, which step2 and step3 are in a conflict. If you have computed L2 distance, why use fc layer again? You can just compare distances. If you really want to use fc layer to compare similarity between 128-dimensional embeddings, just pass these features to fc layer, no need to computer L2. And, sigmoid fc layer with 2 outputs is not a good way, since the train examples will push the output to approximate 0.501 and 0.499 for right and wrong output. For example, if the label is 1, two outputs will be approximate 0.501 for 1 and approximate 0.499 for 0.  That happens since your network wanna get a lower error for your cost function. So if you want to get a confidence for 2-class mission, just use one output rather than two (the closer to 1, more confidence for positive label). 
That's my opion.

**Comment by ahkarami** [comment]
Dear @JudasDie,
Thank you very much for your complete answer. I agree with you about number of outputs of the FC layer (_i.e.,_ just using one output is a better choice, according to your nice opinion and explanation). However, about using the FC layer & L2 distance, I think the distance computation is a correct solution and it is necessary. Because, actually we want to learn a linear regression model by using FC layer on the distances of the two 128-dimensional embeddings. This note, also mentioned in the Lecture Videos of Dr. Andrew Ng (in Coursera). Maybe if one just uses the raw two 128-dimensional embeddings (i.e., 256-dimensional feature vector) and FC layer followed by Sigmoid; then the network works well, but I think the distance of the two embeddings will works better. Finally, We can try & examine it :)
Thank you very much.
